CREATE TABLE tb_identificacion(
ID INT AUTO_INCREMENT NOT NULL,
DESCRIPCION VARCHAR(50) NULL,
PRIMARY KEY (ID)
);

SELECT * FROM tb_identificacion;



INSERT INTO tb_identificacion(DESCRIPCION)
VALUE("Cliente E"),
("Cliente B"),
("Cliente C"),
("Cliente D");

DELETE FROM tb_identificacion WHERE ID = 6;

INSERT INTO tb_identificacion(DESCRIPCION)
VALUE("Cliente G");

INSERT INTO tb_identificacion(ID, DESCRIPCION)
VALUE(100, "Cliente G");

INSERT INTO tb_identificacion(DESCRIPCION)
VALUE("Cliente H");

INSERT INTO tb_identificacion(ID, DESCRIPCION)
VALUE(3, "Cliente B");

INSERT INTO tb_identificacion(ID, DESCRIPCION)
VALUE(NULL, "Cliente I");

CREATE TABLE TAB_IDENTITY2 (ID INT AUTO_INCREMENT, DESCRIPTOR VARCHAR(20), PRIMARY KEY(ID));
INSERT INTO TAB_IDENTITY2 (DESCRIPTOR) VALUES ('CLIENTE1');
INSERT INTO TAB_IDENTITY2 (DESCRIPTOR) VALUES ('CLIENTE2');
INSERT INTO TAB_IDENTITY2 (DESCRIPTOR) VALUES ('CLIENTE3');
INSERT INTO TAB_IDENTITY2 (ID, DESCRIPTOR) VALUES (NULL, 'CLIENTE4');
DELETE FROM TAB_IDENTITY2 WHERE ID = 3;
INSERT INTO TAB_IDENTITY2 (ID, DESCRIPTOR) VALUES (NULL, 'CLIENTE6');
INSERT INTO TAB_IDENTITY2 (ID, DESCRIPTOR) VALUES (NULL, 'CLIENTE7');
DELETE FROM TAB_IDENTITY2 WHERE ID = 2;

SELECT * FROM TAB_IDENTITY2;